version: '3.7'
services:
  nginxproxy:
    image: nginx:alpine
    depends_on:
      - nodehttp1server
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  nodehttp1server:
    image: nodeserverhttp2talk:latest
    # The image server is actually http/1.1 so we use the nginx proxy
    # to connect over http2
    #entrypoint: "tail -f /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - .:/code

  cpphttp2server:
    image: cppserverhttp2talk:latest
    entrypoint: "tail -f /dev/null"
    ports:
      - "3001:3000"
    volumes:
      - .:/code

  myhttp2client:
    image: hermes:latest
    entrypoint: "tail -f /dev/null"
    volumes:
      - .:/code

networks:
  default:
    name: http2-network
    attachable: true
