version: '3.7'
services:
  nodehttp2server:
    image: nodeserverhttp2talk:latest
    entrypoint: "tail -f /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  cpphttp2server:
    image: cppserverhttp2talk:latest
    entrypoint: "tail -f /dev/null"
    ports:
      - "3001:3000"
    volumes:
      - .:/code

  myhttp2client:
    image: hermes:latest
    entrypoint: "tail -f /dev/null"
    volumes:
      - .:/code

networks:
  default:
    name: myhttp2-network
    attachable: true
